### ISSUE TITLE
Incorrect sprite path in icon preview

### ISSUE THREAD

**Issue by jan-herman** [tobimori/kirby-icon-field#18]
Hi there,
when using the sprite option, the icon previews have the wrong sprite path (folder is missing). See the field configuration and screenshot below. The options are loaded correctly from the specified sprite, but the sprite path for the icon preview is wrong.

```yml
label: field.icon.label
type: icon
folder: assets/images
sprite: icons.svg
max: 1
```

![SCR-20241017-nvl](https://github.com/user-attachments/assets/3f2b414f-1505-4643-975e-da1987739bbe)
